[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "myscrcpy"
version = "1.3.2"
authors = [
    {name = "Me2sY", email = "me2sy@outlook.com"}
]
description = "A Scrcpy client implemented using Python, dearpygui/pygame, etc., With video, audio, and controls. Supports UHID Keyboard and Chinese input, key proxy, and more."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["scrcpy", "android", "pyav", "numpy", "Dearpygui", "Pygame"]
license = {text = "MIT"}
classifiers = [
    "Topic :: Scrcpy",
    "Framework :: adbutils",
    "Programming Language :: Python :: 3"
]

dependencies = [
    # Base
    'loguru', 'adbutils',

    # Config Manager
    'tinydb',

    # Video
    'av', 'numpy',

    # Audio
    'pyaudio', 'pyflac',

    # GUI
    'dearpygui', 'pygame', 'pyvirtualcam', 'pyzmq'
]