[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "myscrcpy"
version = "1.2.0"
authors = [
    {name = "Me2sY", email = "me2sy@outlook.com"}
]
description = "A Scrcpy client implemented using the Python language, dearpygui/pygame, etc., with video, audio, and controls. Supports UHID Keyboard and Chinese input, key proxy, and more."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["scrcpy", "android", "pyav", "numpy", ""]
license = {text = "MIT"}
classifiers = [
    "Topic :: Scrcpy",
    "Framework :: adbutils",
    "Programming Language :: Python :: 3"
]

dependencies = [
    'loguru',
    'adbutils',
    # Video
    'av', 'numpy',
    # Audio
    'pyaudio', 'pyflac'
]