[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "myscrcpy"
version = "1.1.0"
authors = [
    {name = "Me2sY", email = "me2sy@outlook.com"}
]
description = "MYScrcpy, A Scrcpy Python Client."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["scrcpy", "android", "pyav"]
license = {text = "MIT"}
classifiers = [
    "Topic :: Scrcpy",
    "Framework :: adbutils",
    "Programming Language :: Python :: 3"
]

dependencies = [
    'loguru',
    'adbutils',
    # Video
    'pyav', 'numpy',
    # Audio
    'pyaudio', 'pyflac',
    # Control
    'pyzmq',
    # GUI
    'dearpygui', 'pygame', 'easygui', 'nicegui', 'opencv-python',
    'click'
]

[tool.setuptools]
py-modules = []